spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
              - Path=/users/**

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/hotels/**,/staffs/**

          - id: RATING-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/ratings/**



server:
  port: 8084



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



