server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: myuser
    password: 09072005
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Hotel-Service

  config:
    import: configserver:http://localhost:8085


#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
